---
- !ruby/object:Rubber::Configuration::InstanceItem
  name: db01
  domain: foo.com
  roles:
  - !ruby/object:Rubber::Configuration::RoleItem
    name: db
    options:
      primary: true
  - !ruby/object:Rubber::Configuration::RoleItem
    name: postgresql
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: postgresql_master
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: collectd
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: monit
    options: {}
  instance_id: i-90e42cf5
  image_type: c1.medium
  image_id: ami-b6089bdf
  security_groups:
  - your_app_name_production_default
  - your_app_name_production_db01
  - your_app_name_production_db
  - your_app_name_production_postgresql
  - your_app_name_production_postgresql_master
  - your_app_name_production_collectd
  - your_app_name_production_monit
  external_host: ec2-54-225-183-12.compute-1.amazonaws.com
  external_ip: 54.225.183.12
  internal_host: ip-10-245-162-208.ec2.internal
  internal_ip: 10.245.162.208
  zone: us-east-1a
  platform: linux
  root_device_type: instance-store
  static_ip: 
- !ruby/object:Rubber::Configuration::InstanceItem
  name: app01
  domain: foo.com
  roles:
  - !ruby/object:Rubber::Configuration::RoleItem
    name: app
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: passenger
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: apache
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: collectd
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: monit
    options: {}
  instance_id: i-96cfbbfe
  image_type: c1.medium
  image_id: ami-b6089bdf
  security_groups:
  - your_app_name_production_default
  - your_app_name_production_app01
  - your_app_name_production_app
  - your_app_name_production_passenger
  - your_app_name_production_apache
  - your_app_name_production_collectd
  - your_app_name_production_monit
  external_host: ec2-54-225-183-55.compute-1.amazonaws.com
  external_ip: 54.225.183.55
  internal_host: ip-10-242-5-140.ec2.internal
  internal_ip: 10.242.5.140
  zone: us-east-1a
  platform: linux
  root_device_type: instance-store
  static_ip: 54.225.183.55
- !ruby/object:Rubber::Configuration::InstanceItem
  name: web01
  domain: foo.com
  roles:
  - !ruby/object:Rubber::Configuration::RoleItem
    name: web
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: haproxy
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: collectd
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: monit
    options: {}
  instance_id: i-62cfbb0a
  image_type: c1.medium
  image_id: ami-b6089bdf
  security_groups:
  - your_app_name_production_default
  - your_app_name_production_web
  - your_app_name_production_web01
  - your_app_name_production_haproxy
  - your_app_name_production_collectd
  - your_app_name_production_monit
  external_host: ec2-54-225-180-216.compute-1.amazonaws.com
  external_ip: 54.225.180.216
  internal_host: ip-10-194-118-138.ec2.internal
  internal_ip: 10.194.118.138
  zone: us-east-1a
  platform: linux
  root_device_type: instance-store
  static_ip: 54.225.180.216
- !ruby/object:Rubber::Configuration::InstanceItem
  name: production
  domain: foo.com
  roles:
  - !ruby/object:Rubber::Configuration::RoleItem
    name: apache
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: app
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: passenger
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: collectd
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: common
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: monit
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: db
    options:
      primary: true
  - !ruby/object:Rubber::Configuration::RoleItem
    name: postgresql
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: postgresql_master
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: elasticsearch
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: examples
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: graphite_server
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: graphite_web
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: graylog_elasticsearch
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: graylog_mongodb
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: mongodb
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: graylog_server
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: graylog_web
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: haproxy
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: web
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: web_tools
    options: {}
  instance_id: i-ecd38986
  image_type: c1.medium
  image_id: ami-b6089bdf
  security_groups:
  - your_app_name_production_default
  - your_app_name_production_web
  - your_app_name_production_web_tools
  - your_app_name_production_production
  - your_app_name_production_apache
  - your_app_name_production_app
  - your_app_name_production_passenger
  - your_app_name_production_collectd
  - your_app_name_production_common
  - your_app_name_production_monit
  - your_app_name_production_db
  - your_app_name_production_postgresql
  - your_app_name_production_postgresql_master
  - your_app_name_production_elasticsearch
  - your_app_name_production_examples
  - your_app_name_production_graphite_server
  - your_app_name_production_graphite_web
  - your_app_name_production_graylog_elasticsearch
  - your_app_name_production_graylog_mongodb
  - your_app_name_production_mongodb
  - your_app_name_production_graylog_server
  - your_app_name_production_graylog_web
  - your_app_name_production_haproxy
  external_host: ec2-54-225-183-12.compute-1.amazonaws.com
  external_ip: 54.225.183.12
  internal_host: ip-10-102-63-160.ec2.internal
  internal_ip: 10.102.63.160
  zone: us-east-1a
  platform: linux
  root_device_type: instance-store
  static_ip: 
- volumes: {}
  static_ips:
    app01: 54.225.183.55
    web01: 54.225.180.216
